[package]
name = "reconnect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.5.1"
env_logger = "0.10.0"
rand = "0.8.5"
serial_test = "2.0.0"

[dependencies]
postgres = "0.19.5"
