version: "3.8"

services:
  postgres:
    container_name: recon-postgresql
    image: postgres:14.1-alpine
    command: >
      -c work_mem=1GB
      -c max_wal_size=8GB
    restart: always
    volumes:
      - ${PWD}/bench_data:/var/lib/postgresql/bench_data:delegated
    ports:
      - '5432:5432'
    expose:
      - '5432'
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${RECON_POSTGRES_DBNAME}
      - POSTGRES_USER=${RECON_POSTGRES_USER}
      - POSTGRES_PASSWORD=${RECON_POSTGRES_PASSWORD}
    tty: true
    networks:
      - local

#  mysql:
#    container_name: recon-mysql
#    image: mysql:8.0.27
#    command: >
#      --default-authentication-plugin=mysql_native_password
#      --binlog-cache-size=16M
#      --key_buffer_size=0
#      --max_connections=1000
#      --innodb_flush_log_at_trx_commit=2
#      --innodb_flush_log_at_timeout=10
#      --innodb_log_compressed_pages=OFF
#      --sync_binlog=0
#    restart: always
#    volumes:
#      - mysql-data:/var/lib/mysql:db_data
#    user: mysql
#    ports:
#      - '3306:3306'
#    expose:
#      - '3306'
#    env_file:
#      - .env
#    tty: true
#    networks:
#      - local


volumes:
  postgresql-data:
  mysql-data:

networks:
  local:
    driver: bridge